# default
spring:
  profiles:
    active: local
    # default로 사용할 프로필 선택 (local)

logging:
  level:
    root: INFO
    org.springframework.batch.item.database: DEBUG
    okhttp3: WARN

---

spring:
  config:
    activate:
      on-profile: local

#  batch:
#    job:
#      name: SpringBootBatchDemo

#    jdbc:
#      initialize-schema: always  # 배치 애플리케이션 초기화시에 메타데이터와 관련된 스키마도 같이 초기화 되도록 한다.
#      # spring5.0 이후 @EnableBatchProceesing을 사용하면 위 옵션을 막아 생성이 안된다.
#      platform: mariadb

  # datasource_h2:
  h2:
    console:
      enabled: true       # H2 콘솔을 활성화하여 웹 브라우저에서 H2 데이터베이스를 확인할 수 있도록 한다.
      path: /h2-console   # H2 콘솔의 경로를 설정한다. 기본값은 /h2-console 이다. (http://localhost:8080/h2-console)

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true  # Hibernate가 생성하는 SQL을 로그에 출력하도록 설정한다. false로 설정하면 SQL 로그가 출력되지 않는다.
    hibernate:
      ddl-auto: create-drop   # ddl-auto: create-drop # 개발 환경에서만 사용, 프로덕션 환경에서는 사용하지 않는다.
                              # create-drop: 애플리케이션 시작 시 데이터베이스를 생성하고, 종료 시 삭제한다.

  datasource_mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/spring_batch_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    url: jdbc:mysql://localhost:3307/demo
    username: neodain
    password: Kht72@eye1 

  datasource_maraidb:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/demo
    username: neodain
    password: Kht72@eye1 # single datasource 가 아닌 여러개의 datasource를 사용할 경우, 별도의 configuration 파일에서 datasource의 사용을 설정한다면 {{MARIADB_PASSWORD}}로 설정 가능하다.
    # password: {{MARIADB_PASSWORD}} // application.yml에서 설정 할 경우, {{MARIADB_PASSWORD}}로 설정 : single datasource
  # jpa:
  #   hibernate:
  #     ddl-auto: create-drop 
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.MySQLDialect

influx:
  url: http://localhost:8087
  username: neodain
  password: {{INFLUXDB_PASSWORD}}
  org: neodain 
  bucket: neodain-bucket 
  logLevel: BODY
  readTimeout: 5s
  writeTimeout: 5s
  connectTimeout: 5s

