# default
spring:
  profiles:
    active: local
    # default로 사용할 프로필 선택 (local)

logging:
  level:
    root: INFO
    org.springframework.batch.item.database: DEBUG
    okhttp3: WARN

---

spring:
  config:
    activate:
      on-profile: local

#  batch:
#    job:
#      name: SpringBootBatchDemo

#    jdbc:
#      initialize-schema: always  # 배치 애플리케이션 초기화시에 메타데이터와 관련된 스키마도 같이 초기화 되도록 한다.
#      # spring5.0 이후 @EnableBatchProceesing을 사용하면 위 옵션을 막아 생성이 안된다.
#      platform: mariadb

  datasource_mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/spring_batch_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    url: jdbc:mysql://localhost:3307/demo
    username: neodain
    password: Kht72@eye1

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/demo
    username: neodain
    password: Kht72@eye1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

influx:
  url: http://localhost:8087
  username: neodain
  password: Kht72@eye1
  org: neodain 
  bucket: neodain-bucket 
  logLevel: BODY
  readTimeout: 5s
  writeTimeout: 5s
  connectTimeout: 5s

