### templates/configmap.yaml
{{ $root := . }}
{{- range .Values.batchTasks.tasks }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $root.Release.Name }}-{{ .name }}-config
  labels:
    {{- include "batch-task.labels" $root | nindent 4 }}
data:
  application.yml: |
    application:
      name: {{ .name }}
    spring:
      cloud:
        task:
          name: {{ .name }} {{/* name: {{ include "selectByName" (list "task_name" .env) }} */}}
        jdbc:
          platform: mariadb
      datasource: {{/* task meta db */}}
        driver-class-name: org.mariadb.jdbc.Driver 
        url: jdbc:mariadb://neo-batch-task.neodain.svc.cluster.local:3306/demo
      datasource_reader: {{/* 외부 DB로부터 read하기 위한 DB정보 */}}
        driver-class-name: {{ .datasource.driver_class_name }}
        url: {{ .datasource.url }}
        username: {{ .datasource.username }}
        password: {{ .datasource.password }}
{{- if eq .datasource_sub.enabled true }}
      datasource_reader_sub: {{/* 외부의 db로 부터 read하기 위한 정보(sub) */}}
        driver_class_name: {{ .datasource_sub.driver_class_name }}
        url: {{ .datasource_sub.url }}
        username: {{ .datasource_sub.username }}
        password: {{ .datasource_sub.password }}
{{- end }}
    influx:
      url: {{ .influx.url }}
{{- if $root.Values.influxdb }}
{{- if $root.Values.influxdb.env }}
{{- range $root.Values.influxdb.env }}
      {{- if eq .name "DOCKER_INFLUXDB_INIT_ORG" }}
      org: {{ .value }}
      {{- end }}
      {{- if eq .name "DOCKER_INFLUXDB_INIT_BUCKET" }}
      bucket: {{ .value }}
      {{- end }}
      {{- if eq .name "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN" }}
      token: {{ .value }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
      logLevel: {{ .influx.logLevel }}
      readTimeout: {{ .influx.readTimeout }}
      writeTimeout: {{ .influx.writeTimeout }}
      connectTimeout: {{ .influx.connectTimeout }}
    logging:
      level:
        root: INFO
        org.springframework.batch.item.database: DEBUG
        org.springframework.cloud.task: DEBUG
{{- end }}
