{{- /* charts/batch-task/templates/configmap-env.yaml */ -}}
{{- $root := . -}}
{{- range .Values.batchTasks.tasks }}
{{- $res := include "batch-task.resname" (dict "root" $root "name" .name) -}}
{{- $hasDS  := hasKey . "datasource" -}}
{{- $hasDSS := and (hasKey . "datasource_sub") .datasource_sub -}}
{{- $hasIFX := hasKey . "influx" -}}
{{- if or $hasDS $hasDSS $hasIFX }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $res }}-env
  labels:
    {{- include "batch-task.labels" $root | nindent 4 }}
data:
  {{- if $hasDS }}
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "{{ .datasource.driver_class_name }}"
  SPRING_DATASOURCE_URL: "{{ .datasource.url }}"
  SPRING_DATASOURCE_USERNAME: "{{ .datasource.username }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .datasource.password }}"
  {{- end }}
  {{- if and $hasDSS .datasource_sub.enabled }}
  SPRING_DATASOURCE_SUB_DRIVER_CLASS_NAME: "{{ .datasource_sub.driver_class_name }}"
  SPRING_DATASOURCE_SUB_URL: "{{ .datasource_sub.url }}"
  SPRING_DATASOURCE_SUB_USERNAME: "{{ .datasource_sub.username }}"
  SPRING_DATASOURCE_SUB_PASSWORD: "{{ .datasource_sub.password }}"
  {{- end }}
  {{- if $hasIFX }}
  INFLUX_TOKEN: "{{ .influx.token }}"
  INFLUX_URL: "{{ .influx.url }}"
  INFLUX_LOG_LEVEL: "{{ .influx.logLevel }}"
  INFLUX_READ_TIMEOUT: "{{ .influx.readTimeout }}"
  INFLUX_WRITE_TIMEOUT: "{{ .influx.writeTimeout }}"
  INFLUX_CONNECT_TIMEOUT: "{{ .influx.connectTimeout }}"
  {{- end }}
---
{{- end }}
{{- end }}