## templates/deployment.yaml (공통 템플릿)
{{- $root := . }}
{{- range .Values.batchTasks.tasks }}
{{- if or (eq .mode "deployment") .deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "batch-task.resname" (dict "root" $root "name" .name) }}
  labels:
    {{- include "batch-task.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  replicas: {{ .replicaCount | default 1 }} 
  selector:
    matchLabels:
      {{- include "batch-task.selectorLabels" $root | nindent 6 }}
      app.kubernetes.io/component: {{ .name }}
  template:
    metadata:
      labels:
        {{- include "batch-task.selectorLabels" $root | nindent 8 }}
        app.kubernetes.io/component: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy | default "IfNotPresent" }}

          {{- with .command }}   # // with를 사용할 경우, command 체크 후 내용 출력.
          command: {{ toJson . }}
          {{- end }}

          {{- with .args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          envFrom:
            - configMapRef:
                name: {{ include "batch-task.resname" (dict "root" $root "name" .name) }}-config
            - secretRef:
                name: {{ include "batch-task.resname" (dict "root" $root "name" .name) }}-secret
                optional: true 
                {{/* # Secret 없을 때도 기동되도록 완충 */}}

          {{- with .env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .resources }}
          resources:
            requests:
              cpu: {{ .requests.cpu | default "100m" | quote }}
              memory: {{ .requests.memory | default "128Mi" | quote }}
            limits:
              cpu: {{ .limits.cpu | default "500m" | quote }}
              memory: {{ .limits.memory | default "512Mi" | quote }}
          {{- end }}

          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .livenessProbe }}
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
          {{- end }}

          {{- with .readinessProbe }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
          {{- end }}
      {{- with .volumes }}   
      # 컨테이너 외부에서 ConfigMap을 마운트하려면 volumeMounts와 
      # valumes 둘 다 설정 필요.
      volumes:
        {{- toYaml . | nindent 12 }}
      {{/*
      volumes:
        - name: config-volume
          configMap:
            name: {{ .configMap.name | default (printf "%s-config" (include "batch-job.resname" (dict "root" $root "name" .name))) }}
      */}}
      {{- end }}

      restartPolicy:
        {{ .restartPolicy | default "Always" }} 

      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}

      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }} 
      {{- end }}

      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
