## templates/deployment.yaml (공통 템플릿)
{{- $root := . }}
{{- range .Values.batchTasks.tasks }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $root.Release.Name }}-{{ .name }} {{/* name: {{ include "batch-task.fullname" $root }} */}}
  labels:
    {{- include "batch-task.labels" $root | nindent 4 }}
spec:
  replicas: {{ .replicaCount }} 
  selector:
    matchLabels:
      app: {{ .name }} {{/* app: {{ include "batch-task.name" $root }} */}}
  template:
    metadata:
      labels:
        app: {{ .name }} {{/* app: {{ include "batch-task.name" $root }} */}}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
          args: {{ toJson .arguments }}
          env:
{{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
{{- end }}
          args: {{/* args: {{ toJson .arguments }} */}}
{{- range .command }}
            - {{ . | quote }}
{{- end }}
          ports:
            - containerPort: {{ .service.port }}
          envFrom:
            - configMapRef:
                name: {{ $root.Release.Name}}-{{ .name }}-config
            - secretRef:
                name: {{ $root.Release.Name}}-{{ .name }}-secret
          resources:
            limits:
              memory: {{ .resources.limits.memory }}
              cpu: {{ .resources.limits.cpu }}
            requests:
              memory: {{ .resources.requests.memory }}
              cpu: {{ .resources.requests.cpu }}
          volumeMounts:
{{- range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
{{- end }}
          livenessProbe: 
            {{- toYaml .livenessProbe | nindent 12 }}
          readinessProbe: 
            {{- toYaml .readinessProbe | nindent 12 }}
      volumes:
{{- if .configMap.enabled }}
        - name: config-volume 
          configMap:
            name: {{ $root.Release.Name }}-{{ .configMap.name }}
{{- end }}
      restartPolicy: 
        {{ .restartPolicy | default "Never" }}
      nodeSelector: 
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity: {{/* affinity: {{- toYaml .affinity | nindent 8 }} */}}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - {{ .nodeSelector.role }}
      tolerations: 
        {{- toYaml .tolerations | nindent 8 }}
{{- end }}
