{{- $root := . -}}
{{- range $i, $task := .Values.batchTasks.tasks }}
{{- if and $task.service.enabled (eq (default "deployment" $task.mode) "deployment") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "batch-task.resname" (dict "root" $root "name" $task.name) }}
  labels:
    {{- include "batch-task.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $task.name }}
spec:
  type: {{ default "ClusterIP" $task.service.type }}
  selector:
    {{- include "batch-task.selectorLabels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $task.name }}
  ports:
    - name: {{ default "http" $task.service.name | lower }}
      port: {{ int $task.service.port }}
      targetPort: {{ int (default $task.service.port $task.service.targetPort) }}
      {{- if and (eq (default "ClusterIP" $task.service.type) "NodePort") $task.service.nodePort }}
      nodePort: {{ int $task.service.nodePort }}
      {{- end }}
{{- end }}
{{- end }}
