{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    {{- include "batch-infra.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.admin.user | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.admin.password | quote }}
          volumeMounts:
            - name: grafana-storage
              mountPath: {{ .Values.grafana.persistence.mountPath }}
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: {{ .Values.grafana.persistence.existingClaim }}
      nodeSelector: {{- toYaml .Values.grafana.nodeSelector | nindent 8 }}
{{- end }}
