{{- if .Values.mariadb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    {{- include "batch-infra.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy | default "IfNotPresent" }}
          env:
            {{- range .env }}
            - name: {{ .env.name }}
              value: {{ .env.value }}
            {{- end }}
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-storage
              mountPath: {{ .Values.mariadb.persistence.mountPath }} {{/* /var/lib/mariadb */}}
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
      nodeSelector: {{- toYaml .Values.mariadb.nodeSelector | nindent 8 }}
{{- end }}
