{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    {{- include "batch-infra.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy | default "IfNotPresent" }}
          env:
            {{- range .Values.mysql.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.mysql.service.port }} {{/* 3306 */}}
          volumeMounts:
            - name: mysql-storage
              mountPath:
                {{ .Values.mysql.persistence.mountPath }} {{/* /var/lib/mysql */}}
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      nodeSelector: {{- toYaml .Values.mysql.nodeSelector | nindent 8 }}
{{- end }}
