# templates/scdf-server-service.yaml
{{- if .Values.scdf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: scdf-server
  labels:
    {{- include "batch-infra.labels" . | nindent 4 }}
spec:
  type: {{ .Values.scdf.server.service.type }}
  ports:
    - port: 9393
      targetPort: 9393
      nodePort: {{ .Values.scdf.server.service.nodePort }}
  selector:
    app: scdf-server
{{- end }}
