# templates/skipper-deployment.yaml
{{- if .Values.scdf.skipper.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skipper
  labels:
    {{- include "batch-infra.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skipper-server
  template:
    metadata:
      labels:
        app: skipper-server
    spec:
      containers:
        - name: skipper
          image: {{ .Values.scdf.skipper.image.repository }}:{{ .Values.scdf.skipper.image.tag | default "2.11.5" }}
          imagePullPolicy: {{ .Values.scdf.skipper.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 7577
          env:
            {{- range .Values.scdf.skipper.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources: {{- toYaml .Values.scdf.skipper.resources | nindent 12 }}
      nodeSelector: {{- toYaml .Values.scdf.skipper.nodeSelector | nindent 8 }}
{{- end }}

