{{- /* charts/batch-job/templates/configmap-env.yaml */ -}}
{{- $root := . -}}
{{- range .Values.batchJobs.jobs }}
{{- $res := include "batch-job.resname" (dict "root" $root "name" .name) -}}
{{- $hasDS  := hasKey . "datasource" -}}
{{- $hasDSS := and (hasKey . "datasource_sub") .datasource_sub -}}
{{- $hasIFX := hasKey . "influx" -}}
{{- if or $hasDS $hasDSS $hasIFX }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $res }}-env
  labels:
    {{- include "batch-job.labels" $root | nindent 4 }}
data:
  {{- if $hasDS }}
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "{{ .datasource.driver_class_name }}"
  SPRING_DATASOURCE_URL: "{{ .datasource.url }}"
  SPRING_DATASOURCE_USERNAME: "{{ .datasource.username }}"
  {{- end }}
  {{- if and $hasDSS .datasource_sub.enabled }}
  APP_DATASOURCE_SUB_DRIVER_CLASS_NAME: "{{ .datasource_sub.driver_class_name }}"
  APP_DATASOURCE_SUB_URL: "{{ .datasource_sub.url }}"
  APP_DATASOURCE_SUB_USERNAME: "{{ .datasource_sub.username }}"
  {{- end }}
  {{- if $hasIFX }}
  APP_INFLUX_URL: "{{ .influx.url }}"
  APP_INFLUX_LOG_LEVEL: "{{ .influx.logLevel }}"
  APP_INFLUX_READ_TIMEOUT: "{{ .influx.readTimeout }}"
  APP_INFLUX_WRITE_TIMEOUT: "{{ .influx.writeTimeout }}"
  APP_INFLUX_CONNECT_TIMEOUT: "{{ .influx.connectTimeout }}"
  {{- end }}
---
{{- end }}
{{- end }}

{{/*
{{- $root := . -}}
{{- range .Values.batchJobs.jobs }}
{{- $res := include "batch-job.resname" (dict "root" $root "name" .name) -}}
{{- if .datasource }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $res }}-config
  labels:
    {{- include "batch-job.labels" $root | nindent 4 }}
data:
  # Spring Boot 기본 데이터소스 바인딩
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "{{ .datasource.driver_class_name }}"
  SPRING_DATASOURCE_URL: "{{ .datasource.url }}"
  SPRING_DATASOURCE_USERNAME: "{{ .datasource.username }}"
  {{- if .datasource_sub.enabled }}
  # 보조 데이터소스가 앱에서 'app.datasource-sub.*' 처럼 커스텀 키를 읽는다면
  APP_DATASOURCE_SUB_DRIVER_CLASS_NAME: "{{ .datasource_sub.driver_class_name }}"
  APP_DATASOURCE_SUB_URL: "{{ .datasource_sub.url }}"
  APP_DATASOURCE_SUB_USERNAME: "{{ .datasource_sub.username }}"
  {{- end }}
  # Influx - 앱에서 어떤 키로 바인딩할지에 맞춰 이름을 정해줘
  APP_INFLUX_URL: "{{ .influx.url }}"
  APP_INFLUX_LOG_LEVEL: "{{ .influx.logLevel }}"
  APP_INFLUX_READ_TIMEOUT: "{{ .influx.readTimeout }}"
  APP_INFLUX_WRITE_TIMEOUT: "{{ .influx.writeTimeout }}"
  APP_INFLUX_CONNECT_TIMEOUT: "{{ .influx.connectTimeout }}"
---
{{- end }}
{{- end }}
*/}}