{{- $root := . -}}
{{- range .Values.batchJobs.jobs }}
{{- if or (eq .mode "job") .job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "batch-job.resname" (dict "root" $root "name" .name) }}
  labels:
    {{- include "batch-job.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  parallelism: {{ .job.parallelism   | default 1 }}
  completions: {{ .job.completions   | default 1 }}
  backoffLimit: {{ .job.backoffLimit | default 0 }}
  {{- if .job.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .job.activeDeadlineSeconds }}
  {{- end }}
  ttlSecondsAfterFinished: {{ .job.ttlSecondsAfterFinished | default 3600 }}
  template:
    metadata:
      labels:
        {{- include "batch-job.selectorLabels" $root | nindent 8 }}
        app.kubernetes.io/component: {{ .name }}
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Never
      {{- with .serviceAccountName }}
      serviceAccountName: {{ . }}
      {{- end }}
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy | default "IfNotPresent" }}
          {{- with .command }}
          command: {{ toJson . }}
          {{- end }}
          {{- with .args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          # ====== 혼용 포인트: ENV/SECRET 일괄 주입 ======
          {{- $envcm := printf "%s-env" (include "batch-job.resname" (dict "root" $root "name" .name)) -}}
          {{- $envcm_exists := (or (and (hasKey . "datasource") .datasource) (and (hasKey . "datasource_sub") .datasource_sub) (hasKey . "influx")) -}}
          envFrom:
            {{- if $envcm_exists }}
            - configMapRef:
                name: {{ $envcm }}
            {{- end }}
            - secretRef:
                name: {{ include "batch-job.resname" (dict "root" $root "name" .name) }}-secret
                optional: true
          # ====== 혼용 포인트: 파일 마운트 (application.yaml 등) ======
          {{- if and .configMap .configMap.enabled .configMap.files }}
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "/config/"
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
          {{- with .volumeMounts }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- else }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          resources:
            requests:
              cpu:    {{ .resources.requests.cpu    | default "200m"  | quote }}
              memory: {{ .resources.requests.memory | default "256Mi" | quote }}
            limits:
              cpu:    {{ .resources.limits.cpu      | default "500m"  | quote }}
              memory: {{ .resources.limits.memory   | default "512Mi" | quote }}
      {{- /* volumes: 파일 기반 ConfigMap일 때만 추가 */ -}}
      {{- if and .configMap .configMap.enabled .configMap.files }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .configMap.name | default (printf "%s-config" (include "batch-job.resname" (dict "root" $root "name" .name))) }}
      {{- end }}
      {{- with .volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}


{{/* 
## templates/job.yaml (공통 템플릿) 
{{- $root := . }}
{{- range .Values.batchJobs.jobs }} # 10개의 batch job을 루프를 통해 자동 Deploy 한다
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "batch-job.resname" (dict "root" $root "name" .name) }}
  labels:
    {{- include "batch-job.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap-file.yaml") . | sha256sum }}
    checksum/env:    {{ include (print $.Template.BasePath "/configmap-env.yaml")  . | sha256sum }}
    checksum/secret: {{ include (print $.Template.BasePath "/secret-env.yaml")     . | sha256sum }}
    # 파일/시크릿이 바뀌면 파드가 자동으로 교체
    # 이러면 application.yaml/env/비밀이 바뀔 때마다 파드가 새로 기동됨.
spec:
  # 동시에 몇 개까지 병렬 실행할지(기본 1)
  parallelism: {{ .job.parallelism   | default 1 }}
  # 전체 완료 개수(기본 1) — 병렬>1이면 batch fan-out 가능
  completions: {{ .job.completions   | default 1 }}
  # 실패 시 재시도 횟수 (0이면 즉시 실패 처리)
  backoffLimit: {{ .job.backoffLimit | default 0 }}
  # 전체 작업 제한 시간(초). 초과 시 Job 실패 처리(옵션)
  {{- if .job.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .job.activeDeadlineSeconds }}
  {{- end }}
  # 완료 후 리소스 자동 정리(초) — TTL Controller (k8s ≥1.21)
  ttlSecondsAfterFinished: {{ .job.ttlSecondsAfterFinished | default 300 }}
  template:
    metadata:
      labels:
        {{- include "batch-job.labels" $root | nindent 8 }}
        app.kubernetes.io/component: {{ .name }}
      {{- with .podAnnotations }} # podAnnotations가 있을 경우, 해당 배열을 출력한다.
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Never  # Job은 반드시 Never/OnFailure 중 하나로 설정.
      {{- with .serviceAccountName }}
      serviceAccountName: {{ . }}
      {{- end }}
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy | default "IfNotPresent" }}
          {{- with .command }}   # // with를 사용할 경우, command 체크 후 내용 출력.
          command: {{ toJson . }}
          {{- end }}
          {{- with .args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "batch-job.resname" (dict "root" $root "name" .name) }}-config
            - secretRef:
                name: {{ include "batch-job.resname" (dict "root" $root "name" .name) }}-secret
                optional: true 
                # Secret 없을 때도 기동되도록 완충 
          {{- with .env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .resources }}
          resources:
            requests:
              cpu: {{ .requests.cpu | default "100m" | quote }}
              memory: {{ .requests.memory | default "128Mi" | quote }}
            limits:
              cpu: {{ .limits.cpu | default "500m" | quote }}
              memory: {{ .limits.memory | default "512Mi" | quote }}
          {{- end }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .livenessProbe }}
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
          {{- end }}
          {{- with .readinessProbe }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
          {{- end }}
      {{- with .volumes }}   
      volumes:
      # 컨테이너 외부에서 ConfigMap을 마운트하려면 volumeMounts와 
      # valumes 둘 다 설정 필요.
      # volumes:
      #  {{- toYaml . | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .configMap.name | default (printf "%s-config" (include "batch-job.resname" (dict "root" $root "name" .name))) }}
      {{- end }}
      restartPolicy:
        {{ .restartPolicy | default "Never" }} 
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }} 
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
*/}}
