{{- /* charts/batch-job/templates/secret-env.yaml */ -}}
{{- $root := . -}}
{{- range .Values.batchJobs.jobs }}
{{- $res := include "batch-job.resname" (dict "root" $root "name" .name) -}}

{{- /* 안전 접근(없을 수 있으니 default) */ -}}
{{- $ds  := .datasource     | default dict -}}
{{- $sub := .datasource_sub | default dict -}}
{{- $ifx := .influx         | default dict -}}

{{- /* 기존 필드 존재 여부 */ -}}
{{- $hasDSU      := (and (hasKey $ds  "username")      (get $ds  "username")) -}}
{{- $hasDSP      := (and (hasKey $ds  "password")      (get $ds  "password")) -}}
{{- $hasDSSU     := (and (hasKey $sub "enabled") $sub.enabled (hasKey $sub "username") (get $sub "username")) -}}
{{- $hasDSSP     := (and (hasKey $sub "enabled") $sub.enabled (hasKey $sub "password") (get $sub "password")) -}}
{{- $hasIFXT     := (and (hasKey $ifx "token")         (get $ifx "token")) -}}

{{- /* "기존 Secret" 제공 여부(있으면 새로 만들지 않음) */ -}}
{{- $hasDSSecret := (and (hasKey $ds  "secretName")     (get $ds  "secretName")) -}}
{{- $hasSubSecret:= (and (hasKey $sub "secretName")     (get $sub "secretName")) -}}
{{- $hasIFXSecret := (and (hasKey $ifx "existingSecret") (get $ifx "existingSecret")) -}}

{{- /* Influx 토큰 키 이름(기본 INFLUX_TOKEN) */ -}}
{{- $ifxTokenKey := default "INFLUX_TOKEN" (get $ifx "tokenKey") -}}

{{- /* 이 템플릿이 Secret을 만들어야 하는지(기존 Secret 없고 평문 값이 있을 때만) */ -}}
{{- $needDS   := and (not $hasDSSecret)  (or $hasDSU  $hasDSP) -}}
{{- $needSub  := and (not $hasSubSecret) (or $hasDSSU $hasDSSP) -}}
{{- $needIFX  := and (not $hasIFXSecret)  $hasIFXT -}}
{{- $needAny  := or $needDS $needSub $needIFX -}}

{{- if $needAny }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $res }}-secret
type: Opaque
stringData:
  {{- /* datasource: 기존 Secret 없을 때만 생성 */ -}}
  {{- if and (not $hasDSSecret) $hasDSU }}
  SPRING_DATASOURCE_USERNAME: "{{ $ds.username }}"
  {{- end }}
  {{- if and (not $hasDSSecret) $hasDSP }}
  SPRING_DATASOURCE_PASSWORD: "{{ $ds.password }}"
  {{- end }}

  {{- /* datasource_sub: 기존 Secret 없을 때만 생성 */ -}}
  {{- if and (not $hasSubSecret) $hasDSSU }}
  SPRING_DATASOURCE_SUB_USERNAME: "{{ $sub.username }}"
  {{- end }}
  {{- if and (not $hasSubSecret) $hasDSSP }}
  SPRING_DATASOURCE_SUB_PASSWORD: "{{ $sub.password }}"
  {{- end }}

  {{- /* influx: existingSecret 없을 때만 생성 */ -}}
  {{- if and (not $hasIFXSecret) $hasIFXT }}
  {{ $ifxTokenKey }}: "{{ $ifx.token }}"
  {{- end }}
---
{{- end }}
{{- end }}