{{- /* charts/batch-job/templates/secret-env.yaml */ -}}
{{- $root := . -}}
{{- range .Values.batchJobs.jobs }}
{{- $res := include "batch-job.resname" (dict "root" $root "name" .name) -}}
{{- $hasDSP := and (hasKey . "datasource") (hasKey .datasource "password") .datasource.password -}}
{{- $hasDSSP := and (hasKey . "datasource_sub") .datasource_sub .datasource_sub.enabled (hasKey .datasource_sub "password") .datasource_sub.password -}}
{{- if or $hasDSP $hasDSSP }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $res }}-secret
type: Opaque
stringData:
  {{- if $hasDSP }}
  SPRING_DATASOURCE_PASSWORD: "{{ .datasource.password }}"
  {{- end }}
  {{- if $hasDSSP }}
  APP_DATASOURCE_SUB_PASSWORD: "{{ .datasource_sub.password }}"
  {{- end }}
---
{{- end }}
{{- end }}