{{- $root := . -}}
{{- range .Values.batchJobs.jobs }}
{{- if .service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "batch-job.resname" (dict "root" $root "name" .name) }}
  labels:
    {{- include "batch-job.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  type: {{ .service.type | default "ClusterIP" }}
  selector:
    {{- include "batch-job.selectorLabels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
  ports:
    - name: {{ .service.name | default "http" | lower }}
      port: {{ .service.port }}
      targetPort: {{ .service.targetPort | default .service.port }}
      {{- if and (eq (.service.type | default "ClusterIP") "NodePort") .service.nodePort }}
      {{/* 서비스 타입이 NodePort이고 nodePort 숫자도 지정돼 있을 때만 nodePort: 라인을 출력하자는 조건문 */}}
      nodePort: {{ .service.nodePort }}
      {{/* nodePort: {{ add .service.nodePort }} # nodePort는 30000–32767 내에서만! */}}
      {{- end }}
{{- end }}
{{- end }}

