{{- $root := . -}}
{{- range .Values.batchJobs.jobs }}
{{- if .service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "batch-job.resname" (dict "root" $root "name" .name) }}
  labels:
    {{- include "batch-job.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  type: {{ .service.type | default "ClusterIP" }}
  selector:
    {{- include "batch-job.selectorLabels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
  ports:
    - name: {{ .service.name | default "http" | lower }}
      port: {{ .service.port }}
      targetPort: {{ .service.targetPort | default .service.port }}
      {{- if and (eq (.service.type | default "ClusterIP") "NodePort") .service.nodePort }}
      nodePort: {{ .service.nodePort }}
      {{- end }}
{{- end }}
{{- end }}

