{{- $root := . }}
{{- range .Values.batchJobs.jobs }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "batch-job.fullname" $root }} # service name으로 사용
  labels:
    {{- include "batch-job.labels" $root | nindent 4 }}
spec:
  type: NodePort # test 목적으로 외부에서 접속가능한 포트로 사용 시 
  selector:
    app: {{ include "batch-job.name" $root }}
  ports:
    - name: TCP 
      port: {{ .service.port }}
      targetPort: {{ .service.port }}
      nodePort: {{ add 30000 .service.port }}
{{- end }}
