# kind-config.yaml
# Kind cluster: 1 control-plane + 2 workers
# - control-plane: NodePort 접근용 포트 매핑만, 기본 테인트 유지
# - worker-1: role=work-1,type=job + taint type=job:NoSchedule
# - worker-2: role=work-2,type=task + taint type=task:NoSchedule

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  # ---------------------------
  # Control-plane
  # ---------------------------
  - role: control-plane
    image: kindest/node:v1.33.1@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f
    # NodePort(30000~32767)를 호스트로 바로 열어 테스트 편의 확보
    extraPortMappings:
      # - containerPort: 31000   # Grafana
      #   hostPort: 31000
      #   protocol: TCP
      # - containerPort: 31090   # Prometheus
      #   hostPort: 31090
      #   protocol: TCP
      # - containerPort: 32080   # SCDF Server
      #   hostPort: 32080
      #   protocol: TCP
      # - containerPort: 32081   # Skipper
      #   hostPort: 32081
      #   protocol: TCP
      - containerPort: 30086   # InfluxDB
        hostPort: 30086
        protocol: TCP

    # ⚠️ 기본 control-plane 테인트는 그대로 둡니다.
    #    파드(Deployment 등) 쪽에서 tolerations:
    #      - key: "node-role.kubernetes.io/control-plane"
    #        operator: "Exists"
    #        effect: "NoSchedule"
    #    로 허용하도록 차트에 이미 반영한 설계 유지.

  # ---------------------------
  # Worker #1  (job 전용)
  # ---------------------------
  - role: worker
    image: kindest/node:v1.33.1@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f
    # labels: // kind cluster에서는 labels 설정이 안먹음
    #   role: work-1
    #   type: job
    # kubeadmConfigPatches: // kind cluster에서는 taint 설정이 안먹음
    #   - |
    #     apiVersion: kubeadm.k8s.io/v1beta4
    #     kind: JoinConfiguration
    #     nodeRegistration:
    #       kubeletExtraArgs:
    #         node-labels: "role=work-1,type=job"
    #       taints:
    #         - key: "type"
    #           value: "job"
    #           effect: "NoSchedule"
    extraPortMappings:
      - containerPort: 30306   # MySQL NodePort (옵션)
        hostPort: 30306
        protocol: TCP

  # ---------------------------
  # Worker #2  (task 전용)
  # ---------------------------
  - role: worker
    image: kindest/node:v1.33.1@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f
    # labels:
    #   role: work-2
    #   type: task
    # kubeadmConfigPatches:
    #   - |
    #     apiVersion: kubeadm.k8s.io/v1beta4
    #     kind: JoinConfiguration
    #     nodeRegistration:
    #       kubeletExtraArgs:
    #         node-labels: "role=work-2,type=task"
    #       taints:
    #         - key: "type"
    #           value: "task"
    #           effect: "NoSchedule"
    extraPortMappings:
      - containerPort: 30307   # MariaDB NodePort (옵션)
        hostPort: 30307
        protocol: TCP