name: Maven Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Test root module
      run: ./mvnw -B test
    - name: Test user_rest module
      working-directory: user_rest
      run: ./mvnw -B test



# name: Hello World

# on: [push]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     #- uses: actions/checkout@v2
#     - name: Run pwd
#       run: pwd
#     - name: Run ls -al
#       run: ls -al