name: Docker Image CI Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    #runs-on: eclipse-temurin:17-jdk
    #runs-on: amazoncorretto:17-alpine-jdk
    runs-on: Ubuntu latest

    steps:
    - uses: actions/checkout@v4
    - name: pwd
      run : pwd
    - name: ls -al
      run : ls -al
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
